// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gncbbbqtmevximlzigsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduY2JiYnF0bWV2eGltbHppZ3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDE3OTMsImV4cCI6MjA2NzcxNzc5M30.qNqiBlKVnbvCM78ncbQ4yYK6J8ANkvBNN8uWXisRArE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});